export const ProductoDataSample = [
  {
    id: 1,
    cod_bar: '991122334422',
    id_nav: 'nav_12',
    id_nav_grupo: 'nav_g_1',
    nombre_producto:
      'Televisor Samsung Con la capacidad para tener 100000 pulgadas y mucho mas contenido',
    descripcion: 'Televisor de 40 pulgadas de la marca Samsung',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: false,
  },
  {
    id: 2,
    cod_bar: '223355667788',
    id_nav: 'nav_1',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Cámara Toshiba',
    descripcion: '',
    ubicacion_almacen: 'Estante 1 Pasillo 2',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 3,
    cod_bar: '123456789012',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Pantalla Gigabyte',
    descripcion: '',
    ubicacion_almacen: 'Estante 2 Pasillo 5',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: false,
    url_prod: '',
    manual_path: '',
    almacenado: false,
  },
  {
    id: 4,
    cod_bar: '123243546576',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Cableado para cámara',
    descripcion: '',
    ubicacion_almacen: 'Estante 1 Pasillo 1',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: false,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 5,
    cod_bar: '009988776655',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Placa de conexión',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 1',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: false,
  },
  {
    id: 6,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 7,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 8,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 9,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 10,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 11,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 12,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 13,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 14,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 15,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 16,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 17,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 18,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 19,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 20,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
  {
    id: 21,
    cod_bar: '102938477561',
    id_nav: '',
    id_nav_grupo: 'nav_g_2',
    nombre_producto: 'Televisor Samsung',
    descripcion: '',
    ubicacion_almacen: 'Estante 3 Pasillo 10',
    fecha_alta: '1642008302695',
    fecha_baja: '',
    activo: true,
    url_prod: '',
    manual_path: '',
    almacenado: true,
  },
];
