export const ProyectosDataSample = [
  {
    id: 1,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera1',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
  {
    id: 2,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera2',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
  {
    id: 3,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera3',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
  {
    id: 4,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera4',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
  {
    id: 5,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera5',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
  {
    id: 6,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera6',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
  {
    id: 7,
    id_nav_proyecto: 'nav_12',
    comercial: 'Paco Gonzalez',
    cliente: 'Naviera7',
    direccion: 'Cuntis de Arriba',
    provincia: 'Madrid',
    contacto_nombre: 'Manolito Fernandez',
    contacto_telefono: '123789456',
    contacto_email: 'manolito@manolo.com',
  },
];
